# ==============================================================================
# PROYECTO: Yelp Lead Master Pro
# DESCRIPCIÓN: Módulo de Notificaciones y Envío de Correo (SMTP + ENV)
# DESCRIPTION: Notification and Email Delivery Module (SMTP + ENV)
# DESARROLLADO POR / DEVELOPED BY: VICTOR ARMANDO DE OLIVEIRA RODRÍGUEZ
# ==============================================================================

import smtplib
import os
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from email.mime.base import MIMEBase
from email import encoders
from dotenv import load_dotenv

# Cargamos las variables del archivo .env
# Load variables from .env file
load_dotenv()


def enviar_reporte_email(ruta_archivo):
    """
    Envía el reporte Excel usando las credenciales del archivo .env.
    Sends the Excel report using credentials from the .env file.
    """
    # --- CONFIGURACIÓN DESDE .ENV / CONFIGURATION FROM .ENV ---
    REMITENTE = os.getenv("EMAIL_USER")
    PASSWORD = os.getenv("EMAIL_PASS")
    DESTINATARIO = os.getenv("EMAIL_RECEIVER")

    if not os.path.exists(ruta_archivo):
        print(f"❌ [ERROR] No se encontró el archivo / File not found: {ruta_archivo}")
        return False

    try:
        # Crear el mensaje / Create the message
        mensaje = MIMEMultipart()
        mensaje['From'] = REMITENTE
        mensaje['To'] = DESTINATARIO
        mensaje['Subject'] = f"📊 Reporte de Leads Extraídos - VICTOR DE OLIVEIRA"

        cuerpo = (
            "Hola,\n\nAdjunto encontrarás el reporte de leads generado por Yelp Lead Master Pro.\n"
            "Hello,\n\nPlease find attached the leads report generated by Yelp Lead Master Pro.\n\n"
            "Atentamente / Sincerely,\n"
            "VICTOR ARMANDO DE OLIVEIRA RODRÍGUEZ"
        )
        mensaje.attach(MIMEText(cuerpo, 'plain'))

        # Adjuntar el archivo Excel / Attach the Excel file
        with open(ruta_archivo, "rb") as adjunto:
            parte = MIMEBase('application', 'octet-stream')
            parte.set_payload(adjunto.read())
            encoders.encode_base64(parte)
            parte.add_header(
                'Content-Disposition',
                f"attachment; filename= {os.path.basename(ruta_archivo)}",
            )
            mensaje.attach(parte)

        # Conexión con el servidor SMTP de Gmail
        # Connection with Gmail SMTP server
        print("📧 [INFO] Conectando con el servidor de correo...")
        server = smtplib.SMTP('smtp.gmail.com', 587)
        server.starttls()
        server.login(REMITENTE, PASSWORD)

        print(f"📤 [INFO] Enviando reporte a / Sending report to: {DESTINATARIO}")
        server.send_message(mensaje)
        server.quit()

        print("✅ [EXITO] Correo enviado correctamente / Email sent successfully.")
        return True

    except Exception as e:
        print(f"❌ [ERROR] Fallo al enviar correo / Email failed: {e}")
        return False